### PR TITLE
Rearrange CSV columns to match cubecomps.com

### PR DESCRIPTION
**Pull request by fw42**
Closes https://github.com/fw42/cubecomp/issues/134

### CODE REVIEW

**Comment by cubizh** [comment]
This is broken for cubecomps.com input usage (the standard nowadays) and needs fixing.
I think the accepted format for cubecomps may have changed to match the WCA competition website CSV export state, which completely breaks what currently exists here.
Cubecomps now directly accepts the following CSV columns format (preferred if this was the output here too). Please notice the space between the words Birth and Date and the name of the events:

`Status,Name,Country,WCA ID,Birth Date,Gender,,333,444,555,222,333bf,333oh,333fm,333ft,minx,pyram,sq1,clock,skewb,666,777,444bf,555bf,333mbf`

The "Status" column is meant to always have the character 'a' for approved competitors and 'p' for pending competitors. I think this is tracked in cubecomp already, just a matter of outputting this here in the export.
Thank you!
The rest is pretty much straightforward.

**Comment by fw42** [comment]
@SAuroux agree?

**Comment by SAuroux** [comment]
I will check back with Luis, the owner of cubecomps.com

2016-03-18 1:04 GMT+01:00 Florian Weingarten <notifications@github.com>:

**Comment by Luis-J-Ianez** [comment]
Hey,

Cubecomps.com can import two kind of registration formats, CSV and XLSX / XLS.  It expects those to be WCA CSV complaint or CubingUSA XLS complaint.  You have samples of both attached in the ZIP.

If I'm informed correctly, CCM will only export CSV, so I think you should focus in this format strictly.  Tags for the events in the CSV are according to the WCA abbreviations: 333, 333oh, minx, pyram,...  It's easy to get all the correct tags in the WCA website (for example by checking the URLs for rankings).

Hope this helps,

Luis

[Registration samples - CSV and XLS.zip](https://github.com/fw42/cubecomp/files/179944/Registration.samples.-.CSV.and.XLS.zip)

**Comment by cubizh** [comment]
It's almost there! The only thing missing is the events default shortcode, that's wrong: instead of `2,3,3b,4,4b,5,5b,6,7,cl,fm,ft,mbf,mx,oh,py,s1,sk` the required are the WCA ones:  `333,444,555,222,333bf,333oh,333fm,333ft,minx,pyram,sq1,clock,skewb,666,777,444bf,555bf,333mbf`

Good job though.

**Comment by fw42** [comment]
Try again please (https://github.com/fw42/cubecomp/commit/90c93364878c9272d62c1634f53e9ef275356c1c).

**Comment by cubizh** [comment]
From my part it's working perfectly, just copy/pasting the information into an editor, saving it as CSV and importing it into cubecomps. By the way, not sure if I should make a formal github feature request or not, but do you think you could provide a link to the output CSV file so it could save this mid editor step? That would save even more work and I think me and @SAuroux would appreciate it :) Thanks!

**Comment by fw42** [comment]
https://github.com/fw42/cubecomp/pull/218

**Pull request merged**
