### PR TITLE
French default theme

### PR DESCRIPTION
**Pull request by SAuroux**
Thanks again to Reto for translating. :)

### CODE REVIEW

**Comment by fw42** [comment]
Awesome. We should do the same for pt.

@cubizh if you have time :-)

**Comment by cubizh** [comment]
I'm not entirely sure what you mean, or if anything is missing, but I've already translated the default theme a while ago: https://github.com/fw42/cubecomp/pull/181

**Comment by fw42** [comment]
oh lol totally forgot about that :) nvm.

**Comment by fw42** [comment]
@SAuroux: This should be available in the admin area now.

**Pull request merged**
